foundation:
  model: "qwen3:1.7b"
  provider: "ollama"
  think: true

targets:
  qwen3_8b_target:
    provider: "ollama"
    model: "qwen3:8b"
    target_type: "text"
    modalities:
      input: [text]
      output: [text]
  qwen3_vl_4b_target:
    provider: "ollama"
    model: "qwen3-vl:4b"
    target_type: "text"
    modalities:
      input: [text]
      output: [text]
